"""Initial database schema

Revision ID: fd7c075d609b
Revises: 
Create Date: 2026-01-22 13:36:00.469872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7c075d609b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_email'), 'participants', ['email'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_participants_name'), 'participants', ['name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_player_id'), 'players', ['player_id'], unique=True)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tourn_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_tournaments_year'), 'tournaments', ['year'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.String(), nullable=False),
    sa.Column('player2_id', sa.String(), nullable=False),
    sa.Column('player3_id', sa.String(), nullable=False),
    sa.Column('player4_id', sa.String(), nullable=False),
    sa.Column('player5_id', sa.String(), nullable=False),
    sa.Column('player6_id', sa.String(), nullable=False),
    sa.Column('rebuy_player_ids', sa.JSON(), nullable=True),
    sa.Column('rebuy_type', sa.String(), nullable=True),
    sa.Column('rebuy_original_player_ids', sa.JSON(), nullable=True),
    sa.Column('weekend_bonus_earned', sa.Boolean(), nullable=True),
    sa.Column('weekend_bonus_forfeited', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('leaderboard_data', sa.JSON(), nullable=True),
    sa.Column('scorecard_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_snapshots_id'), 'score_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_score_snapshots_round_id'), 'score_snapshots', ['round_id'], unique=False)
    op.create_index(op.f('ix_score_snapshots_timestamp'), 'score_snapshots', ['timestamp'], unique=False)
    op.create_table('bonus_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('bonus_type', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_points_bonus_type'), 'bonus_points', ['bonus_type'], unique=False)
    op.create_index(op.f('ix_bonus_points_id'), 'bonus_points', ['id'], unique=False)
    op.create_index(op.f('ix_bonus_points_round_id'), 'bonus_points', ['round_id'], unique=False)
    op.create_table('daily_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_points', sa.Float(), nullable=True),
    sa.Column('bonus_points', sa.Float(), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_scores_date'), 'daily_scores', ['date'], unique=False)
    op.create_index(op.f('ix_daily_scores_id'), 'daily_scores', ['id'], unique=False)
    op.create_index(op.f('ix_daily_scores_round_id'), 'daily_scores', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_scores_round_id'), table_name='daily_scores')
    op.drop_index(op.f('ix_daily_scores_id'), table_name='daily_scores')
    op.drop_index(op.f('ix_daily_scores_date'), table_name='daily_scores')
    op.drop_table('daily_scores')
    op.drop_index(op.f('ix_bonus_points_round_id'), table_name='bonus_points')
    op.drop_index(op.f('ix_bonus_points_id'), table_name='bonus_points')
    op.drop_index(op.f('ix_bonus_points_bonus_type'), table_name='bonus_points')
    op.drop_table('bonus_points')
    op.drop_index(op.f('ix_score_snapshots_timestamp'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_round_id'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_id'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_tournaments_year'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_players_player_id'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_participants_name'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_email'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
